spring:
  profiles:
    active: win
  application:
      name: future-02-testingwork
  http:
    encoding:
      charset: UTF-8
      enabled: true
  mvc:
    view:
      prefix: /
      suffix: .do

server:
  port: 9090
  servlet:
    context-path: /future-02-testingwork/

logging:
  file: /logs/${spring.application.name}.log